import Head from "next/head";
import styles from "@/styles/Home.module.css";
import dynamic from "next/dynamic";

const Product = dynamic(() => import("remote_product/ProductList"), {
  ssr: false,
});

const Basket = dynamic(() => import("remote_basket/Basket"), {
  ssr: false,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Micro Frontend Host App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <h1>Host App</h1>
        <Basket />
        <Product />
      </main>
    </>
  );
}